language: cpp
sudo: false

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
      dist: xenial
    - os: windows
      compiler: msvc
script:
  - cmake .
  - cmake --build .
