name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Projects
      run: cmake -B build
    - name: Build Debug
      run: cmake --build ./build/ --config Debug
    - name: Build Release
      run: cmake --build ./build/ --config Release
    - name: Upload Win32 Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ether_win32
        path: bin/win32
    - name: Upload Library Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ether_lib
        path: bin/lib
